services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
            - ./docker/php/ssl:/etc/ssl
        depends_on:
            - php

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/
            - ./ssl:/etc/ssl
        environment:
            - PHP_INI_DIR=/usr/local/etc/php

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: atte_app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        user: "1000:1000"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=pass
        depends_on:
            - mysql
        ports:
            - 8080:80


